# Generated by Django 5.2 on 2025-05-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lostitem_resolved_at_alter_lostitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
